name: Benchmark DOP

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install build tools
        run: sudo apt update && sudo apt install -y build-essential cmake

      - name: Build project
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: Run benchmark
        run: |
          cd build
          ./dop_benchmark > benchmark_result.txt
          cat benchmark_result.txt

      - name: Save benchmark result
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-output
          path: build/benchmark_result.txt
          retention-days: 30
